name = "story_bakery/state_object"
version = "0.1.0"
license = "MIT"
includes = [
    "pesde.toml",
    "LICENSE",
    "README.md",
    ".pesde/scripts/roblox_sync_config_generator.luau",
    ".pesde/scripts/sourcemap_generator.luau",
    "src/**/*.luau",
    "src/**/*.json",
    "tests/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
Signal = { repo = "https://github.com/StoryBakery/Signal", rev = "main" }
TableUtil = { repo = "https://github.com/StoryBakery/TableUtil", rev = "main" }
CFrameUtil = { repo = "https://github.com/StoryBakery/CframeUtil", rev = "main" }
vide = { name = "centau/vide", version = "^0.3.1-test.1" }
msgpack-luau = { wally = "cipharius/msgpack-luau", version = "^0.3.0" }

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
